# Generated by Django 5.0.1 on 2024-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=80)),
                ('memory', models.IntegerField()),
                ('price', models.FloatField()),
                ('color', models.CharField(default='Black', max_length=30)),
                ('image', models.ImageField(upload_to='phone/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
