# Generated by Django 5.0.1 on 2024-01-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codpi', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='color',
            field=models.CharField(choices=[('pink', 'Pink'), ('black', 'Black'), ('blue', 'Blue')], default='pink', max_length=15),
        ),
    ]
