# Generated by Django 5.0.1 on 2024-01-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codpi', '0005_alter_shop_size_alter_shop_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='brand',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('asics', 'Asics')], default='nike', max_length=80),
        ),
        migrations.AlterField(
            model_name='shop',
            name='color',
            field=models.CharField(choices=[('pink', 'Розовый'), ('black', 'Черный'), ('blue', 'Синий')], default='pink', max_length=15),
        ),
        migrations.AlterField(
            model_name='shop',
            name='style',
            field=models.CharField(choices=[('casual', 'Повседневный'), ('sports', 'Спортивный')], default='sports', max_length=25),
        ),
    ]
