# Generated by Django 5.0.1 on 2024-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codpi', '0007_shop_sportswear_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='memory',
            field=models.IntegerField(max_length=80),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.DecimalField(decimal_places=80, max_digits=80),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(choices=[('samsung', 'Samsung'), ('apple', 'Apple'), ('huawei', 'Huawei'), ('google', 'Google'), ('xiaomi', 'Xiaomi')], max_length=80),
        ),
    ]
