# Generated by Django 5.0.1 on 2024-01-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codpi', '0008_laptop_brand_alter_laptop_memory_alter_laptop_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
