# Generated by Django 5.0.1 on 2024-01-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codpi', '0009_alter_laptop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(choices=[(1, 1000), (2, 2000)], default=1),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(upload_to='image/laptop/'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(upload_to='image/phone/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='image/cloth/'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='codpi.customer')),
            ],
        ),
    ]
