# Generated by Django 5.0.1 on 2024-01-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('genre', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='image/movie/')),
            ],
        ),
    ]
